[package]
name = "reference-image-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# egui = "0.18.1"
eframe = "0.18.0"
# dirs = "4.0.0"
# clipboard-win = "4.4.1"
